# Generated by Django 4.0.3 on 2022-04-10 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import orders.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('status', enumfields.fields.EnumField(default=('shipped',), enum=orders.enums.OrderStatus, max_length=10)),
                ('amount', models.IntegerField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('date_end',),
            },
        ),
    ]
